<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.10</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.soham.selfteaching.spring.ai</groupId>
	<artifactId>spring-ai-mcp-one</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-ai-mcp-one</name>
	<description>Loan Bot MCP Server Prototype</description>
	<url/>
	<licenses>
		<license>
			<name>License Copyrighted</name>
			<url>forbidden-license.host</url>
			<distribution>repo</distribution>
		</license>

	</licenses>
	<developers>
		<developer>
			<id>trainerpb</id>
			<name>Soham Sengupta</name>
			<email>sohamsironline@gmail.com</email>
			<url>https://github.com/trinerpb</url>
			<organization>Personal</organization>
			<organizationUrl>https://in.linkedin.com/in/soham-sengupta-37279825</organizationUrl>
			<roles>
				<role>Architect</role>
				<role>Developer</role>
				<role>Mentor</role>
				<role>Researcher</role>
			</roles>
			<timezone>+5.5</timezone>
		</developer>

	</developers>
	<!--    <scm>-->
	<!--        <connection>scm:git:https://github.com/trainerpb/simple-spring-ai-rag-example</connection>-->
	<!--        <developerConnection>scm:git:ssh://git@github.com:trainerpb/simple-spring-ai-rag-example.git-->
	<!--        </developerConnection>-->
	<!--        <url>https://github.com/soham-sengupta/spring-ai-demo</url>-->
	<!--        <tag>HEAD</tag>-->
	<!--    </scm>-->
	<properties>
		<java.version>25</java.version>
		<spring-ai.version>1.1.2</spring-ai.version>
	</properties>
	<dependencies>


		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-mcp-server-webmvc</artifactId>
		</dependency>


		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>