spring.application.name=spring-ai-mcp-one


######
# Basic Server Info
spring.ai.mcp.server.name=spring-ai-mcp-one
spring.ai.mcp.server.version=1.0.0

spring.ai.mcp.server.enabled=true
# Transport Settings
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC
# Map the handshake to /mcp
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
spring.ai.mcp.server.streamable-http.keep-alive-interval=30s

#
## Ensure the POST endpoint is also mapped correctly
spring.ai.mcp.server.streamable-http.sse-message-endpoint=/mcp/message

logging.level.spring.ai.server=TRACE