spring.application.name=spring-ai-mcp-one


######
# Basic Server Info
spring.ai.mcp.server.name=ice-cream-order-server
spring.ai.mcp.server.version=1.0.0

spring.ai.mcp.server.enabled=true
# Transport Settings
spring.ai.mcp.transport.protocol=STREAMABLE
#spring.ai.mcp.server.sse-endpoint=/mcp
logging.level.spring.ai.server=TRACE