spring.application.name=spring-ai-mcp-one

spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=soham
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# create and update tables automatically
spring.jpa.hibernate.ddl-auto=update

######
# Basic Server Info
spring.ai.mcp.server.name=student-good-assistant-v2
spring.ai.mcp.server.version=1.0.0

# Transport Settings
spring.ai.mcp.transport.protocol=STREAMABLE
#spring.ai.mcp.server.sse-endpoint=/mcp
log.level.spring.ai.mcp=DEBUG